// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8E8xdG9AJVW2vroqoeekFhYLWrDD2kms',
    appId: '1:953382676034:web:1401f6340b5a3154476fdb',
    messagingSenderId: '953382676034',
    projectId: 'carecompanion-955be',
    authDomain: 'carecompanion-955be.firebaseapp.com',
    storageBucket: 'carecompanion-955be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKhzBFbS0jLaGa4-iurorMsOdEy65gMGc',
    appId: '1:953382676034:android:45cab9c0e69fc5ae476fdb',
    messagingSenderId: '953382676034',
    projectId: 'carecompanion-955be',
    storageBucket: 'carecompanion-955be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZNB2odnOFr2XBl3PxkvdYIEvhKv9uXFM',
    appId: '1:953382676034:ios:6ea205229d211a1a476fdb',
    messagingSenderId: '953382676034',
    projectId: 'carecompanion-955be',
    storageBucket: 'carecompanion-955be.firebasestorage.app',
    iosBundleId: 'com.example.carecompanionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZNB2odnOFr2XBl3PxkvdYIEvhKv9uXFM',
    appId: '1:953382676034:ios:6ea205229d211a1a476fdb',
    messagingSenderId: '953382676034',
    projectId: 'carecompanion-955be',
    storageBucket: 'carecompanion-955be.firebasestorage.app',
    iosBundleId: 'com.example.carecompanionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8E8xdG9AJVW2vroqoeekFhYLWrDD2kms',
    appId: '1:953382676034:web:efd79ac5674ae1d3476fdb',
    messagingSenderId: '953382676034',
    projectId: 'carecompanion-955be',
    authDomain: 'carecompanion-955be.firebaseapp.com',
    storageBucket: 'carecompanion-955be.firebasestorage.app',
  );
}
